# Generated by Django 4.1.1 on 2022-09-22 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_logs', '0002_entry'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='date_mod',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='entry',
            name='mod',
            field=models.BooleanField(default=False),
        ),
    ]
